language: node_js

node_js:
- '6'

branches:
  only:
  - master

before_install:
 - npm install -g gulp

script:
  - gulp test

after_success:
  - test $TRAVIS_TEST_RESULT = 0
    && gulp release

script:
- npm run unit
- npm run e2e
- npm run lint
- npm run stylelint
- npm run release

addons:
  sauce_connect: true
